version: '3'

vars:
  ALPINE_VERSION: 3.15.12
  PICO_VERSION: 2.1.1

includes:
  assets: ./tasks/assets.taskfile.yml
  build: ./tasks/build.taskfile.yml

tasks:
  test:
    desc: Run unit tests
    cmds:
      - go test ./...

  lint:
    desc: Run lint checks
    cmds:
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint@latest run --timeout=5m --enable=errcheck --enable=unused

  build:local:
    desc: Build local binaries
    cmds:
      - go build ./cmd/agent
      - go build ./cmd/server
