version: '3'

includes:
  assets: ./tasks/assets.taskfile.yml
  build: ./tasks/build.taskfile.yml

tasks:
  test:
    desc: Run unit tests
    cmds:
      - go test ./...

  lint:
    desc: Run lint checks
    cmds:
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint@latest run --timeout=5m --enable=errcheck --enable=unused

  build:local:
    desc: Build local binaries (current OS)
    deps:
      - build:_check-assets
    cmds:
      - go build -o {{.ROOT_DIR}}/dist/agent {{.ROOT_DIR}}/cmd/agent
      - go build -o {{.ROOT_DIR}}/dist/server {{.ROOT_DIR}}/cmd/server

  build:
    desc: Alias for build:all - build all cross-platform release artifacts
    cmds:
      - task: build:all
